#configuración del servidor
server.port = 8005

#configuracion de CONTEXT PATH
#server.servlet.context-path=/ctrl/Cancion/inicio
#configuracion de la bd oracle
spring.datasource.url =jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=system
spring.datasource.password=p$$w23IAvrTo
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database=ORACLE
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.properties.hibernete.format_sql=TRUE

logging.level.org.hibernate.sql=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Configuracion de SPRING SECURITY ----> USER AND PASSWORD
#spring.security.user.name=ADMIN
#spring.security.user.password=123456






